[blocked_hosts]
search = `netscout_indexes` sourcetype="netscout:aed" "|Blocked Host|"

[change_log]
search = `netscout_indexes` sourcetype="netscout:aed" "|Change Log|"

[bandwidth]
search = `netscout_indexes` sourcetype="netscout:aed" "|Bandwidth|"

[infrastructure_interface]
search = `netscout_indexes` sourcetype="netscout:aed" "|Infrastructure|" "msg=Interface" ("is down." OR "is up")

[infrastructure]
search = `netscout_indexes` sourcetype="netscout:aed" "|Infrastructure|"

[cloud]
search = `netscout_indexes` sourcetype="netscout:aed" "|Cloud Signaling|"
