[eventtype=blocked_hosts]
ids = enabled
attack = enabled

[eventtype=change_log]
change = enabled
audit = enabled
endpoint = enabled

[eventtype=infrastructure_interface]
change = enabled
network = enabled
